### PR TITLE
mapexplorer-*: reverse reference arrow

### PR DESCRIPTION
**Pull request by such**
and various improvements:
- deselect on click outside a segment
- factorize svg markers into mapexplorer-core

capture d ecran 2018-03-15 a 17 45 06
capture d ecran 2018-03-15 a 17 45 01
capture d ecran 2018-03-15 a 17 44 53

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/js-indigocore/255)

### CODE REVIEW

**Comment by simonvadee** [comment]
Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[packages/mapexplorer-core/src/ChainTree.js, line 155 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/255#-L7edwaT_heFxbzvDYqF:-L7edwaT_heFxbzvDYqG:bj43y41) ([raw file](https://github.com/stratumn/js-indigocore/blob/0930f3702d2cc1b73244aba290dbdb6683d07863/packages/mapexplorer-core/src/ChainTree.js#L155)):*
> ```JavaScript
>           this
>         );
>         event.stopPropagation();
> ```

what's this for ?

---

*[packages/mapexplorer-core/src/ChainTreeBuilder.js, line 58 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/255#-L7ee71TbYOiLw474Ouk:-L7ee71TbYOiLw474Oul:bb6mt9b) ([raw file](https://github.com/stratumn/js-indigocore/blob/0930f3702d2cc1b73244aba290dbdb6683d07863/packages/mapexplorer-core/src/ChainTreeBuilder.js#L58)):*
> ```JavaScript
>     }
>     if (link.target.data.parentRef === link.source.data.meta.linkHash) {
>       return 'referenced by';
> ```

:+1:

---

*[packages/react-mapexplorer/rollup.config.js, line 24 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/255#-L7eefin5Ejl1-u4Cn4E:-L7eefin5Ejl1-u4Cn4F:b6cajbf) ([raw file](https://github.com/stratumn/js-indigocore/blob/0930f3702d2cc1b73244aba290dbdb6683d07863/packages/react-mapexplorer/rollup.config.js#L24)):*
> ```JavaScript
>     'react-dom',
>     'prop-types',
>     '@indigoframework/mapexplorer-core',
> ```

is this fine for `react-mapexplorer/example` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/255)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[packages/mapexplorer-core/src/ChainTree.js, line 155 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/255#-L7edwaT_heFxbzvDYqF:-L7efzH797aooAPjTm4h:bvjf9vv) ([raw file](https://github.com/stratumn/js-indigocore/blob/0930f3702d2cc1b73244aba290dbdb6683d07863/packages/mapexplorer-core/src/ChainTree.js#L155)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

what's this for ?
</blockquote></details>

now that I've added a onclick handler on the svg we must make sure it isn't called when we click on a segment

---

*[packages/react-mapexplorer/rollup.config.js, line 24 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/255#-L7eefin5Ejl1-u4Cn4E:-L7eg7oGEkD55konRFQB:bsijspx) ([raw file](https://github.com/stratumn/js-indigocore/blob/0930f3702d2cc1b73244aba290dbdb6683d07863/packages/react-mapexplorer/rollup.config.js#L24)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

is this fine for `react-mapexplorer/example` ?
</blockquote></details>

it makes it so that lerna uses a symbolic link for mapexplorer-core as well... But it will make everything fail actually (because webpack, because mjs), I'll remove it.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/255)*

**Comment by such** [comment]
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

*[packages/react-mapexplorer/rollup.config.js, line 24 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/255#-L7eefin5Ejl1-u4Cn4E:-L7eiw8h1LgZOvcDhrmP:b-896fix) ([raw file](https://github.com/stratumn/js-indigocore/blob/0930f3702d2cc1b73244aba290dbdb6683d07863/packages/react-mapexplorer/rollup.config.js#L24)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

it makes it so that lerna uses a symbolic link for mapexplorer-core as well... But it will make everything fail actually (because webpack, because mjs), I'll remove it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/255)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/255#-:-L7hwMndnIZRV6mO1QBK:bnfp4nl)*

**Pull request merged**
