### PR TITLE
Sign segments in agent-ui

### PR DESCRIPTION
**Pull request by simonvadee**
It is now possible to import a key (json format) on the homepage of agent-ui.
 
screen shot 2018-03-02 at 10 14 39

When creating a map or a segment, the user can chose to send a signature.

screen shot 2018-03-02 at 10 17 33

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/js-indigocore/242)

### CODE REVIEW

**Comment by bejito** [comment]
Reviewed 8 of 47 files at r1.
Review status: 8 of 47 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[packages/agent-client-js/src/sign.js, line 18 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6apqgV6Fd6QWBz57Ca:-L6apqgV6Fd6QWBz57Cb:b2hy7jb) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-client-js/src/sign.js#L18)):*
> ```JavaScript
> 
> import { sign as naclSign } from 'tweetnacl';
> /* eslint-disable */
> ```

nit: you can disable the linter for a single line
```// eslint-disable-next-line import/extensions```
```


---

*[packages/agent-client-js/src/withKey.js, line 48 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6aq83l9XUFaTgul91o:-L6aq83l9XUFaTgul91p:bhzt30x) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-client-js/src/withKey.js#L48)):*
> ```JavaScript
>     );
>   }
>   return true;
> ```

why do you need to return something here ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242)*
<!-- Sent from Reviewable.io -->

**Comment by bejito** [comment]
Reviewed 35 of 47 files at r1.
Review status: 43 of 47 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/actions/uploadKey.js, line 19 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6arkJu3rs2fHnut2Ty:-L6arkJu3rs2fHnut2Tz:bazs1fg) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-ui/src/actions/uploadKey.js#L19)):*
> ```JavaScript
> });
> 
> export const deleteKey = () => dispatch => {
> ```

Is there a reason `deleteKetEvent` and `deleteKey` are separated ?

---

*[packages/agent-ui/src/components/keyManager.js, line 36 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6asTn11kWCNwSUEWKt:-L6asTn11kWCNwSUEWKu:ba5uvif) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-ui/src/components/keyManager.js#L36)):*
> ```JavaScript
>       <div style={{ display: 'flex' }}>
>         <Dropzone
>           onDrop={(accepted, rejected) => this.onDrop(accepted, rejected)}
> ```

`this.onDrop` is defined only with one argument

---

*[packages/agent-ui/src/components/keyManager.js, line 50 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6aszrH8S7WTBIS-Sgk:-L6aszrH8S7WTBIS-Sgl:biamhb6) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-ui/src/components/keyManager.js#L50)):*
> ```JavaScript
>         </Dropzone>
>         {userKey && userKey.public ? (
>           <Card style={{ display: 'flex', marginLeft: '2em' }}>
> ```

omg inline styles  :scream: 

---

*[packages/agent-ui/src/containers/signedAttributes.js, line 17 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6au9Nf5XakY231Bm3B:-L6au9Nf5XakY231Bm3C:b-r7tdfs) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-ui/src/containers/signedAttributes.js#L17)):*
> ```JavaScript
>     this.state = {
>       signed: false,
>       attributes: {
> ```

I'm not sure you need to keep these in the state... 
Maybe I'm missing something but isn't it possible to directly update the store and display its values ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242)*

**Comment by bejito** [comment]
Reviewed 4 of 47 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242)*

**Comment by simonvadee** [comment]
Review status: 38 of 48 files reviewed at latest revision, 6 unresolved discussions.

---

*[packages/agent-client-js/src/sign.js, line 18 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6apqgV6Fd6QWBz57Ca:-L6b6ZIeeK9h9N1TiL2R:by6co1o) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-client-js/src/sign.js#L18)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

nit: you can disable the linter for a single line
```// eslint-disable-next-line import/extensions```

</blockquote></details>

you know your stuff when it comes to disable the linter ;)

---

*[packages/agent-client-js/src/withKey.js, line 48 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6aq83l9XUFaTgul91o:-L6av_B0zP66KYnIUp8v:bjup15u) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-client-js/src/withKey.js#L48)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

why do you need to return something here ?
</blockquote></details>

I don't, fixed.

---

*[packages/agent-ui/src/actions/uploadKey.js, line 19 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6arkJu3rs2fHnut2Ty:-L6avngKu4aDtsPyY2zD:b-d8xmc7) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-ui/src/actions/uploadKey.js#L19)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

Is there a reason `deleteKetEvent` and `deleteKey` are separated ?
</blockquote></details>

nope, fixed.

---

*[packages/agent-ui/src/components/keyManager.js, line 36 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6asTn11kWCNwSUEWKt:-L6avx-289ed99l4vVPV:b-896fix) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-ui/src/components/keyManager.js#L36)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

`this.onDrop` is defined only with one argument
</blockquote></details>

Done.

---

*[packages/agent-ui/src/components/keyManager.js, line 50 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6aszrH8S7WTBIS-Sgk:-L6b7xxXNKRCgCe8GwaQ:b-xgg2sh) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-ui/src/components/keyManager.js#L50)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

omg inline styles  :scream: 
</blockquote></details>

it adds a little spice to the code don't you think ? (fixed)

---

*[packages/agent-ui/src/containers/signedAttributes.js, line 17 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6au9Nf5XakY231Bm3B:-L6b6ISAP48pGB0zT_fA:b8hmyd) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-ui/src/containers/signedAttributes.js#L17)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

I'm not sure you need to keep these in the state... 
Maybe I'm missing something but isn't it possible to directly update the store and display its values ?

</blockquote></details>

It's complicated to have them directly in the store but I used a const instead for the default values.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/242)*

**Comment by bejito** [comment]
Review status: 38 of 48 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[packages/agent-client-js/src/sign.js, line 18 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6apqgV6Fd6QWBz57Ca:-L6bPQbL2AcRmD-vt8WL:b-wbwdj1) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-client-js/src/sign.js#L18)):*
<details><summary><i>Previously, simonvadee wrote…</i></summary><blockquote>

you know your stuff when it comes to disable the linter ;)
</blockquote></details>

haha I have been at war with the linter for decades :)

---

*[packages/agent-ui/src/components/keyManager.js, line 50 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6aszrH8S7WTBIS-Sgk:-L6bPlFdUFXCMw-g-DD3:b-vboo9d) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-ui/src/components/keyManager.js#L50)):*
<details><summary><i>Previously, simonvadee wrote…</i></summary><blockquote>

it adds a little spice to the code don't you think ? (fixed)
</blockquote></details>



---

*[packages/agent-ui/src/containers/signedAttributes.js, line 17 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6au9Nf5XakY231Bm3B:-L6bPnxXlaASdmqCzF7s:b-8fx2u7) ([raw file](https://github.com/stratumn/js-indigocore/blob/07ccb84a63f47bcbed7caf26d57528a1925469d4/packages/agent-ui/src/containers/signedAttributes.js#L17)):*
<details><summary><i>Previously, simonvadee wrote…</i></summary><blockquote>

It's complicated to have them directly in the store but I used a const instead for the default values.
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/242)*

**Comment by bejito** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/242)*

**Comment by bejito** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/signedAttributes.js, line 11 at r2](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6bPxV-skYHkcP4eAt_:-L6bPxV-skYHkcP4eAta:b29fpf4) ([raw file](https://github.com/stratumn/js-indigocore/blob/b5fc58c05e8b7c5658ac085d192608988dd73f00/packages/agent-ui/src/containers/signedAttributes.js#L11)):*
> ```JavaScript
> 
> import { updateSignedAttributes } from '../actions';
> // import signedAttributes from '../reducers/signedAttributes';
> ```

nit: unused

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-:-L6bQ2sSoAbDn5VKhN5H:bnfp4nl)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/containers/signedAttributes.js, line 11 at r2](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6bPxV-skYHkcP4eAt_:-L6bQbM_FhGNdOcyBYl5:b-896fix) ([raw file](https://github.com/stratumn/js-indigocore/blob/b5fc58c05e8b7c5658ac085d192608988dd73f00/packages/agent-ui/src/containers/signedAttributes.js#L11)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

nit: unused
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/242)*

**Comment by jeremie-stratumn** [comment]
Reviewed 38 of 47 files at r1, 8 of 10 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[packages/agent-ui/src/components/keyManager.test.js, line 28 at r3](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6qMtUiAydgxMij6Rz_:-L6qMtUiAydgxMij6Rza:b7wpe1v) ([raw file](https://github.com/stratumn/js-indigocore/blob/5d92bb654d0a3eb5c7e1ca87b397cea48aa3af7a/packages/agent-ui/src/components/keyManager.test.js#L28)):*
> ```JavaScript
>   });
> 
>   it('calls addKey when uploading a json file', () => {
> ```

I think you are testing the behavior of react dropzone here.. I would mock dropzone instead and trust that it will automatically trigger a call to `onDrop` when files are dropped. So basically, I would directly test the behavior of `KeyManager.onDrop`

---

*[packages/agent-ui/src/components/keyManager.test.js, line 37 at r3](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6qNlo-2oHbMqIDWLmC:-L6qNlo-2oHbMqIDWLmD:b-8ojy12) ([raw file](https://github.com/stratumn/js-indigocore/blob/5d92bb654d0a3eb5c7e1ca87b397cea48aa3af7a/packages/agent-ui/src/components/keyManager.test.js#L37)):*
> ```JavaScript
>       }
>     });
>     setTimeout(() => expect(requiredProps.addKey.callCount).to.equal(1), 20);
> ```

I don't think you can rely on this for travis testing..

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-ui/src/components/keyManager.test.js, line 28 at r3](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6qMtUiAydgxMij6Rz_:-L6qgVjpMiyFFIXIPIZM:b-896fix) ([raw file](https://github.com/stratumn/js-indigocore/blob/5d92bb654d0a3eb5c7e1ca87b397cea48aa3af7a/packages/agent-ui/src/components/keyManager.test.js#L28)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I think you are testing the behavior of react dropzone here.. I would mock dropzone instead and trust that it will automatically trigger a call to `onDrop` when files are dropped. So basically, I would directly test the behavior of `KeyManager.onDrop`
</blockquote></details>

Done.

---

*[packages/agent-ui/src/components/keyManager.test.js, line 37 at r3](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6qNlo-2oHbMqIDWLmC:-L6qgY2UjLWhE1qFCNow:b-896fix) ([raw file](https://github.com/stratumn/js-indigocore/blob/5d92bb654d0a3eb5c7e1ca87b397cea48aa3af7a/packages/agent-ui/src/components/keyManager.test.js#L37)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I don't think you can rely on this for travis testing..
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/242)*

**Comment by such** [comment]
looks slick!

---

Reviewed 37 of 47 files at r1, 7 of 10 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[packages/agent-client-js/src/sign.js, line 19 at r4](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6qq67T7cXG-B2SY8ai:-L6qq67T7cXG-B2SY8aj:b-qxb4l1) ([raw file](https://github.com/stratumn/js-indigocore/blob/ce9709e925d37e6318fb41cdb7ebb6651aac3ed2/packages/agent-client-js/src/sign.js#L19)):*
> ```JavaScript
> import { sign as naclSign } from 'tweetnacl';
> // eslint-disable-next-line import/extensions
> import { stringify } from 'canonicaljson/lib/canonicaljson.js';
> ```

do we really need that now?

---

*[packages/agent-ui/src/components/keyManager.js, line 34 at r4](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6qmr_a80UNLWow7rWY:-L6qmr_a80UNLWow7rWZ:b-htq08m) ([raw file](https://github.com/stratumn/js-indigocore/blob/ce9709e925d37e6318fb41cdb7ebb6651aac3ed2/packages/agent-ui/src/components/keyManager.js#L34)):*
> ```JavaScript
> 
>   render() {
>     const { userKey, classes } = this.props;
> ```

you could add `deleteKey` as well.

---

*[packages/cs-validator/test/integration/MapValidator.test.js, line 29 at r4](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-L6qploeALB3fy2nZNgq:-L6qplof1ReEbsgWDvCw:b-sqr2vb) ([raw file](https://github.com/stratumn/js-indigocore/blob/ce9709e925d37e6318fb41cdb7ebb6651aac3ed2/packages/cs-validator/test/integration/MapValidator.test.js#L29)):*
> ```JavaScript
>   describe('With a valid map', () => {
>     it('validates the linkHash', done =>
>       Promise.all(Object.values(validate(validMap))).then(() => done()));
> ```

`done` should not be need here since you return a Promise

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/242#-:-L6qm7Rl8S6qW3P7zSr5:bc71wqi)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[packages/agent-client-js/src/sign.js, line 19 at r4](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6qq67T7cXG-B2SY8ai:-L6r9xbqc9Gw5oUW8Cut:bxmdx59) ([raw file](https://github.com/stratumn/js-indigocore/blob/ce9709e925d37e6318fb41cdb7ebb6651aac3ed2/packages/agent-client-js/src/sign.js#L19)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

do we really need that now?
</blockquote></details>

unfortunately, webpack3 (used by `create-react-app`), does not handle mjs yet (see https://github.com/webpack/webpack/issues/5686). However webpack4 does, and has been released not that long ago, it will be integrated into `create-react-app` pretty soon I guess (https://github.com/facebook/create-react-app/issues/3878)

---

*[packages/agent-ui/src/components/keyManager.js, line 34 at r4](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6qmr_a80UNLWow7rWY:-L6r4omPrfTB1ylpgWLk:b-896fix) ([raw file](https://github.com/stratumn/js-indigocore/blob/ce9709e925d37e6318fb41cdb7ebb6651aac3ed2/packages/agent-ui/src/components/keyManager.js#L34)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

you could add `deleteKey` as well.
</blockquote></details>

Done.

---

*[packages/cs-validator/test/integration/MapValidator.test.js, line 29 at r4](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6qploeALB3fy2nZNgq:-L6r4vaKaRVO1d2gPPH0:bkhh7fy) ([raw file](https://github.com/stratumn/js-indigocore/blob/ce9709e925d37e6318fb41cdb7ebb6651aac3ed2/packages/cs-validator/test/integration/MapValidator.test.js#L29)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

`done` should not be need here since you return a Promise
</blockquote></details>

I had a build error on travis telling me something like `timeout exceeded, 2000ms, is the done() callback called ?`, and I encountered this on several other tests, does it remind you of something ?

(I'm removing `done`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/242)*

**Comment by such** [comment]
Review status: 46 of 47 files reviewed at latest revision, 3 unresolved discussions.

---

*[packages/cs-validator/test/integration/MapValidator.test.js, line 29 at r4](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6qploeALB3fy2nZNgq:-L6rBmp-beo2yoerqSKp:b-3x4jgt) ([raw file](https://github.com/stratumn/js-indigocore/blob/ce9709e925d37e6318fb41cdb7ebb6651aac3ed2/packages/cs-validator/test/integration/MapValidator.test.js#L29)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

I had a build error on travis telling me something like `timeout exceeded, 2000ms, is the done() callback called ?`, and I encountered this on several other tests, does it remind you of something ?

(I'm removing `done`)
</blockquote></details>

it's just that the test is too slow and there's a 2s timeout. Calling `done()` doesn't change anything if it's just slow...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/242)*

**Comment by simonvadee** [comment]
Review status: 46 of 47 files reviewed at latest revision, 2 unresolved discussions.

---

*[packages/cs-validator/test/integration/MapValidator.test.js, line 29 at r4](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-L6qploeALB3fy2nZNgq:-L6rCgyg01lMlx8mXK8b:b2ni9b4) ([raw file](https://github.com/stratumn/js-indigocore/blob/ce9709e925d37e6318fb41cdb7ebb6651aac3ed2/packages/cs-validator/test/integration/MapValidator.test.js#L29)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

it's just that the test is too slow and there's a 2s timeout. Calling `done()` doesn't change anything if it's just slow...
</blockquote></details>

ok!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/242)*

**Comment by jeremie-stratumn** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r4, 1 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/242#-:-L6uGTLIjoQQLtd44fPe:bnfp4nl)*

**Pull request merged**
