### PR TITLE
Agent handles signatures

### PR DESCRIPTION
**Pull request by simonvadee**
# In this PR:

Changes affect both `agent-js`and `agent-client-js` since the former is a dependency of the latter.

## AGENT_JS:
- the agent has been updated to handle signatures coming from the agent-client. This is not a big change, `process.createMap` and `process.createSement` now take an additional `signatures` argument (I will factorize `signatures`and `refs` in an other PR) 
- the plugin `actionArgs`, which inserted `action` and `args` in `link.meta` has been removed. the `action` and `inputs` (formerly `args`) are now automatically added by `processify()`.
- the `this.append(state, meta, type)` takes a new `type` argument which will be used for transition validation.

## AGENT_CLIENT_JS
- a new `withKey()` method has been added (bound to a process/segment, same as `withRefs()`. It takes a `key` argument of the following format: 
```javascript
* @param {object} key - a key object
* @param {string} key.type - the signature scheme that should be used with this key (eg: ed25519)
* @param {string} key.secret - the base64-encoded private key (64 bytes long)
```
- a new `sign()`method has been aded (bound to a process/segment). It takes a `properties` argument which describe what are the fields that should be sign. It format is:
```javascript
 * @param {object} data - a segment (or a process in case of a new map) to be signed.
 * @param {bool} [data.inputs] - user-defined inputs (action arguments).
 * @param {bool} [data.prevLinkHash] - previous link hash of a segment.
 * @param {bool} [data.refs] - references of a segment.
```

I wanted to use the `libp2p-crypto` library that support both ED25519 and RSA but I had a shitload of build issues, therefore I went back to `tweetnacl`.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/js-indigocore/238)

### CODE REVIEW

**Comment by jeremie-stratumn** [comment]
Good job overall! Couple comments below. Could you update READMEs as well?

---

Reviewed 36 of 37 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[packages/agent-client-js/src/sign.js, line 31 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rXtM-Afyd3Uufi5xH:-L5rXtM058oyoWOiv73_:btvi20z) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L31)):*
> ```JavaScript
>  * Each property maps to a boolean saying wether or not it should be signed.
>  * @param {object} obj - a segment (or a process in case of a new map) to be signed.
>  * @param {object} data - a segment (or a process in case of a new map) to be signed.
> ```

I think the argument name is wrong here and below. should be `properties` no?

---

*[packages/agent-client-js/src/sign.js, line 51 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rYSam2pqmm-dm-8tp:-L5rYSam2pqmm-dm-8tq:biqxmn7) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L51)):*
> ```JavaScript
>   return Object.assign(obj, {
>     signed: properties || {
>       inputs: true,
> ```

why do you set `inputs` and `refs` to true? It seems you are not reading `properties` for that matter.

---

*[packages/agent-client-js/src/sign.js, line 115 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rZxf--cj2Eio7760o:-L5rZxf--cj2Eio7760p:b42ikjg) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L115)):*
> ```JavaScript
>       publicKey: key.public,
>       signature: Buffer.from(signature).toString('base64'),
>       payload: payloadPath
> ```

why do you return the `payloadPath` and not the `payload`? if you actually want to return `path` of properties that have been signed, I suggest you change the name of the field as `payload` is misleading

---

*[packages/agent-client-js/src/sign.js, line 119 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5r_5R7D7YGiGhaXdXD:-L5r_5R7D7YGiGhaXdXE:b2yeh2c) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L119)):*
> ```JavaScript
>   });
> 
> export { sign, signedProperties };
> ```

You can do this in a more ES6 friendly way :)
```
export const signedProperties = (obj properties) => ...
...
export const sign = (key, data) => ...
...
```

---

*[packages/agent-client-js/src/withKey.js, line 26 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5r_mSvB7VoSN48JSdA:-L5r_mSvB7VoSN48JSdB:b-n5v2cq) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/withKey.js#L26)):*
> ```JavaScript
> 
> /**
>  * Signs a payload
> ```

this description is misleading as you are not actually signing anything..

---

*[packages/agent-client-js/test/segmentify.js, line 17 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rbVHM8-NhZQUYBi6h:-L5rbVHNDRVfsQ7jsh8k:b6raow2) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/test/segmentify.js#L17)):*
> ```JavaScript
> */
> 
> import { sign as nacl } from 'tweetnacl';
> ```

Are you mocking `nacl` anywhere?

---

*[packages/agent-client-js/test/sign.js, line 112 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rbvC7E3pjeotb7rZO:-L5rbvC7E3pjeotb7rZP:b-vrq4v) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/test/sign.js#L112)):*
> ```JavaScript
>         type: 'ed25519',
>         secret:
>           'yFQwrc9r3afEjXJgPCWmrsDFIu74kpzeO45JlvT0DR/DMi29TsL0kD4ljTNHo65MntarqAYF4iprgkGTRkVuCw=='
> ```

It seems that you are testing nacl lib features here.. no?

---

*[packages/agent-js/src/processify.js, line 59 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rdBBS696j9QjZHHvX:-L5rdBBS696j9QjZHHvY:b-wlx7at) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-js/src/processify.js#L59)):*
> ```JavaScript
>   getSegment
> ) {
>   let link = { ...(initialLink || {}) };
> ```

be careful with the spread operator as it does not deep copy.. I wonder if that might change some behavior down the road. The spread op only copies the top level fields, not the nested one. same below for `link.state` and `meta`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-:-L5reE5wBRQOCRLjX1vx:b-2w7h1z)*

**Comment by simonvadee** [comment]
Review status: 31 of 39 files reviewed at latest revision, 8 unresolved discussions.

---

*[packages/agent-client-js/src/sign.js, line 31 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rXtM-Afyd3Uufi5xH:-L5rewLSAQAVCu3ZQ5pT:bs1ls24) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L31)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I think the argument name is wrong here and below. should be `properties` no?
</blockquote></details>

right!
Done.

---

*[packages/agent-client-js/src/sign.js, line 51 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rYSam2pqmm-dm-8tp:-L5rf7fB9Vo9AnK5fjKT:b-b7n4m1) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L51)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

why do you set `inputs` and `refs` to true? It seems you are not reading `properties` for that matter.
</blockquote></details>

if properties is null/undefined, default values are used instead.

---

*[packages/agent-client-js/src/sign.js, line 115 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rZxf--cj2Eio7760o:-L5rfMwd6HIlcu1PBpXW:b-o9tjof) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L115)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

why do you return the `payloadPath` and not the `payload`? if you actually want to return `path` of properties that have been signed, I suggest you change the name of the field as `payload` is misleading
</blockquote></details>

as defined in SRP2, `signature.payload` is the JMESPATH query that identify which part of the link are signed. Since what is returned here is the actual signature that will be inserted in the link, I cannot change the name of the field. I understand that it might be misleading, I will replace `payload`by `payloadData`and `payloadPath` by `payload`

---

*[packages/agent-client-js/src/sign.js, line 119 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5r_5R7D7YGiGhaXdXD:-L5rg_Aq9DX2iJHLoA62:bb6mt9b) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L119)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

You can do this in a more ES6 friendly way :)
```
export const signedProperties = (obj properties) => ...
...
export const sign = (key, data) => ...
...
```
</blockquote></details>

:+1:

---

*[packages/agent-client-js/src/withKey.js, line 26 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5r_mSvB7VoSN48JSdA:-L5rgh5T2bo8XC9J0w_w:bmrp4mm) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/withKey.js#L26)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

this description is misleading as you are not actually signing anything..
</blockquote></details>

forgot to replace the description, thank's

---

*[packages/agent-client-js/test/segmentify.js, line 17 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rbVHM8-NhZQUYBi6h:-L5roWk64WFo9Az2g9fu:b4x8ogm) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/test/segmentify.js#L17)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

Are you mocking `nacl` anywhere?
</blockquote></details>

no (see other comment about `nacl` testing)

---

*[packages/agent-client-js/test/sign.js, line 112 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rbvC7E3pjeotb7rZO:-L5rnyxB6N9ssmJA2Ka1:b-we25io) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/test/sign.js#L112)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

It seems that you are testing nacl lib features here.. no?
</blockquote></details>

(as discussed IRL) yes I'm testing nacl here, but also that our usage of the library is correct. It's more integration testing than unit testing but since we don't have the former on indigo, I'l let this as it is.

---

*[packages/agent-js/src/processify.js, line 59 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rdBBS696j9QjZHHvX:-L5rk6h6BfARIz6p_r2x:b-4do89u) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-js/src/processify.js#L59)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

be careful with the spread operator as it does not deep copy.. I wonder if that might change some behavior down the road. The spread op only copies the top level fields, not the nested one. same below for `link.state` and `meta`
</blockquote></details>

I think it might cause issues when creating 2 segments on the same processified object indeed.. I'm changing that back. Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238)*

**Comment by jeremie-stratumn** [comment]
Reviewed 8 of 8 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[packages/agent-client-js/README.md, line 187 at r3](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5sdaY3EhOunv5LsJD8:-L5sdaY3EhOunv5LsJD9:b-50ycbm) ([raw file](https://github.com/stratumn/js-indigocore/blob/61d4bb2eb8c264c95959a4b45ba98708cc2e8691/packages/agent-client-js/README.md#L187)):*
> ```Markdown
> 
>     // you could also have added references to the first segment:
>     // return process.withKey(key).sign({refs: true}).withRefs('abc123').createMap('A new map, with references');
> ```

no need to comment here i think..?

---

*[packages/agent-client-js/src/sign.js, line 31 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rXtM-Afyd3Uufi5xH:-L5sdwTw1V4LThzzXpVk:b-1yxa4k) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L31)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

right!
Done.
</blockquote></details>

and also all the ones below
```
[data.action]
[data.inputs]
...
```

---

*[packages/agent-client-js/src/sign.js, line 51 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rYSam2pqmm-dm-8tp:-L5se9Ui-bWz9pyoTbss:b-mgcchm) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L51)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

if properties is null/undefined, default values are used instead.
</blockquote></details>

oh right, so by default you sign them all. cool.

---

*[packages/agent-client-js/src/sign.js, line 115 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rZxf--cj2Eio7760o:-L5sec3XCI8cdB43rpRy:b32wtd) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L115)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

as defined in SRP2, `signature.payload` is the JMESPATH query that identify which part of the link are signed. Since what is returned here is the actual signature that will be inserted in the link, I cannot change the name of the field. I understand that it might be misleading, I will replace `payload`by `payloadData`and `payloadPath` by `payload`
</blockquote></details>

ok

---

*[packages/agent-client-js/test/sign.js, line 112 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rbvC7E3pjeotb7rZO:-L5semUg4zkffZLKWETO:bq0ncok) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/test/sign.js#L112)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

(as discussed IRL) yes I'm testing nacl here, but also that our usage of the library is correct. It's more integration testing than unit testing but since we don't have the former on indigo, I'l let this as it is.
</blockquote></details>

sounds good

---

*[packages/agent-js/src/processify.js, line 59 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rdBBS696j9QjZHHvX:-L5seqE51aoHFz6ueApc:byzenl2) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-js/src/processify.js#L59)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

I think it might cause issues when creating 2 segments on the same processified object indeed.. I'm changing that back. Done.
</blockquote></details>

cool, thanks. I've had issues like this before.. not fun to debug :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238)*

**Comment by simonvadee** [comment]
Review status: 38 of 39 files reviewed at latest revision, 6 unresolved discussions.

---

*[packages/agent-client-js/README.md, line 187 at r3](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5sdaY3EhOunv5LsJD8:-L5ss6PE9E-PO6JdeSo6:b-545e83) ([raw file](https://github.com/stratumn/js-indigocore/blob/61d4bb2eb8c264c95959a4b45ba98708cc2e8691/packages/agent-client-js/README.md#L187)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

no need to comment here i think..?
</blockquote></details>

It should be valid javascript, and there is a `return` statement just before that. (it's done the same way in the example above).

---

*[packages/agent-client-js/src/sign.js, line 31 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rXtM-Afyd3Uufi5xH:-L5sraXh2vSe0ToyfmN2:b-896fix) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L31)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

and also all the ones below
```
[data.action]
[data.inputs]
...
```
</blockquote></details>

Done.

---

*[packages/agent-client-js/src/sign.js, line 115 at r2](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5rZxf--cj2Eio7760o:-L5srmV5ABLipSF4olGC:b-896fix) ([raw file](https://github.com/stratumn/js-indigocore/blob/6770b30604286916d006711b28faaa219992468d/packages/agent-client-js/src/sign.js#L115)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

ok
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238)*

**Comment by alexppxela** [comment]
Reviewed 32 of 37 files at r1, 8 of 8 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238)*

**Comment by alexppxela** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-:-L5t3Ygz0HdM_WhSi1Fs:bnfp4nl)*

**Comment by jeremie-stratumn** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[packages/agent-client-js/README.md, line 187 at r3](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-L5sdaY3EhOunv5LsJD8:-L5tVszK65ORaAWmovSU:b32wtd) ([raw file](https://github.com/stratumn/js-indigocore/blob/61d4bb2eb8c264c95959a4b45ba98708cc2e8691/packages/agent-client-js/README.md#L187)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

It should be valid javascript, and there is a `return` statement just before that. (it's done the same way in the example above).
</blockquote></details>

ok

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/238#-:-L5tVwyl9oGeDMOUTmPg:bnfp4nl)*

**Pull request merged**
