### PR TITLE
cs-validator: verify ed25519 signatures

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/js-indigocore/239)

### CODE REVIEW

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/239#-:-L5x5mbxtK6sez6ST9HE:bnfp4nl)*

**Comment by such** [comment]
Reviewed 14 of 14 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[packages/cs-validator/karma.conf.js, line 78 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/239#-L5xUIltv8NHnx8GK1vh:-L5xUIltv8NHnx8GK1vi:b-29y8kn) ([raw file](https://github.com/stratumn/js-indigocore/blob/677bc4b87aced98bdc79c77f13975d6bb579c0fc/packages/cs-validator/karma.conf.js#L78)):*
> ```JavaScript
>     // - IE (only Windows; has to be installed with `npm install karma-ie-launcher`)
>     browsers: ['Chrome'],
>     // browsers: ['Chrome', 'PhantomJS'],
> ```

doesn't work anymore in PhantomJS?

---

*[packages/cs-validator/src/SegmentValidator.js, line 111 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/239#-L5xUXXsTnNyWNH3w9n9:-L5xUXXsTnNyWNH3w9nA:b-g7xo4m) ([raw file](https://github.com/stratumn/js-indigocore/blob/677bc4b87aced98bdc79c77f13975d6bb579c0fc/packages/cs-validator/src/SegmentValidator.js#L111)):*
> ```JavaScript
>   const publicKeyBytes = Buffer.from(publicKey, 'base64');
>   if (publicKeyBytes.length !== nacl.publicKeyLength) {
>     return `secret key length must be ${nacl.secretKeyLength}, got ${publicKeyBytes.length}`;
> ```

*public key length and `nacl.publicKeyLength` 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/239)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[packages/cs-validator/karma.conf.js, line 78 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/239#-L5xUIltv8NHnx8GK1vh:-L5xclJEjQ7wcsQ46Exd:b-fh96mw) ([raw file](https://github.com/stratumn/js-indigocore/blob/677bc4b87aced98bdc79c77f13975d6bb579c0fc/packages/cs-validator/karma.conf.js#L78)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

doesn't work anymore in PhantomJS?
</blockquote></details>

yes of course, forgot to change that back. Done.

---

*[packages/cs-validator/src/SegmentValidator.js, line 111 at r1](https://reviewable.io:443/reviews/stratumn/js-indigocore/239#-L5xUXXsTnNyWNH3w9n9:-L5xd8BqaBzumedJJZ-L:b-896fix) ([raw file](https://github.com/stratumn/js-indigocore/blob/677bc4b87aced98bdc79c77f13975d6bb579c0fc/packages/cs-validator/src/SegmentValidator.js#L111)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

*public key length and `nacl.publicKeyLength` 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/239)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/239#-:-L5xxrZp93pkUq_B32Cs:bnfp4nl)*

**Pull request merged**
