### PR TITLE
agent, client, ui: error handling fixes

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/js-indigocore/251)

### CODE REVIEW

**Comment by bejito** [comment]
:lgtm: once tests are fixed

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/js-indigocore/251#-:-L7ddxRb_Akbkgq3LAne:b-6wmq87)*

**Comment by such** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[packages/agent-client-js/src/segmentify.js, line 28 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/251#-L7dfp8v2ylQfqTgH8TX:-L7dfp8v2ylQfqTgH8TY:b-mgba6a) ([raw file](https://github.com/stratumn/js-indigocore/blob/a2817590b17009d7197727a56ae7d78424f169a6/packages/agent-client-js/src/segmentify.js#L28)):*
> ```JavaScript
>     const { signed, refs, key } = segment;
> 
>     // canonicaljson does not handle serializing 'undefined', use null instead
> ```

if it's a bug we could fix it in canonicaljson...

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/251)*

**Comment by such** [comment]
*[packages/agent-client-js/src/segmentify.js, line 28 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/251#-L7dfp8v2ylQfqTgH8TX:-L7dg6Vh9XIiB34F9FVj:b-vipbud) ([raw file](https://github.com/stratumn/js-indigocore/blob/a2817590b17009d7197727a56ae7d78424f169a6/packages/agent-client-js/src/segmentify.js#L28)):*
Since it works with `JSON` and that canonicaljson API is supposed to mimic it, I'd say it's a bug:
```
node
> JSON.stringify(undefined)
undefined
> JSON.stringify(null)
'null'
```

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/251)*

**Comment by simonvadee** [comment]
Review status: 3 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[packages/agent-client-js/src/segmentify.js, line 28 at r1](https://beta.reviewable.io/reviews/stratumn/js-indigocore/251#-L7dfp8v2ylQfqTgH8TX:-L7dyiEV7cF3JlXIB2gH:b-896fix) ([raw file](https://github.com/stratumn/js-indigocore/blob/a2817590b17009d7197727a56ae7d78424f169a6/packages/agent-client-js/src/segmentify.js#L28)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

Since it works with `JSON` and that canonicaljson API is supposed to mimic it, I'd say it's a bug:
```
node
> JSON.stringify(undefined)
undefined
> JSON.stringify(null)
'null'
```
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/251)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/js-indigocore/251#-:-L7e0svn2F_UtHTPLX_W:bnfp4nl)*

**Pull request merged**
